### ISSUE TITLE
upgrade to @tsconfig/node18@1.0.2 works only with typescript 5

### ISSUE THREAD

**Issue by atombrenner** [tsconfig/bases#173]
This commit f1b121941952ee8518759b1fc30335762f747855  sets the lib compiler option to `es2023`: 

```
  "compilerOptions": {
    "lib": ["es2023"],
```

But `es2023` is not a valid option for typescript < 5.0. That means by updating a patch version you are receiving this error

```
TSError: ⨯ Unable to compile TypeScript:

node_modules/@tsconfig/node18/tsconfig.json(6,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2019.intl', 'es2020.bigint', 'es2020.date', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2020.number', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'es2021.intl', 'es2022.array', 'es2022.error', 'es2022.intl', 'es2022.object', 'es2022.sharedmemory', 'es2022.string', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.
```

You can fix this by upgrading to  typescript > 5.0. Which might not be possible for all projects, because other dependencies (storybook 6 in my case) do not work with typescript 5.
A patch level update should not be breaking, and maybe it should be noted that it only works with typescript 5.0.

**Comment by RobinTail** [comment]
`+1`

I'm getting this error having `@tsconfig/node18:latest` and `typescript:4.9.4`

```
ts-node quick-start.ts
    .../node_modules/ts-node/src/index.ts:859
        return new TSError(diagnosticText, diagnosticCodes, diagnostics);
               ^
    TSError: ⨯ Unable to compile TypeScript:
    node_modules/@tsconfig/node18/tsconfig.json(6,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020'...
```
